before_script:
  - docker info

build_image:
  script:
   # - docker stop gitlab_gitlab_1
    - docker build --cpu-shares=100 --memory=1024m -t  acteurs-de-la-transition-client:prod .
    - docker stop  acteurs-de-la-transition-client
    - docker rm  acteurs-de-la-transition-client
    - cd /home/debian/docker/acteurs-de-la-transition/
    - docker-compose up -d
   # - docker start gitlab_gitlab_1
  only:
    - master

  script:
    - cd /home/debian/docker/acteurs-de-la-transition-recette/
    - docker-compose down
  #   - docker rm  acteurs-de-la-transition-client-recette
    - docker build --cpu-shares=100 --memory=1024m -t  acteurs-de-la-transition-client:recette .
    - docker-compose up -d
   # - docker exec -it acteurs-de-la-transition-server npx sequelize --env production db:migrate
  only:
    - develop