before_script:
  - docker info

variables:
  SESSION_SECRET: "$SESSION_SECRET"
  EMAIL_USER: "$EMAIL_USER"
  EMAIL_PORT: "$EMAIL_PORT"
  EMAIL_PASSWORD: "$EMAIL_PASSWORD"
  EMAIL_HOST: "$EMAIL_HOST"
  EMAIL_FROM: "$EMAIL_FROM"

build_image:
  script:
    - docker build --build-arg NEXT_PUBLIC_SEO_DISABLED=$NEXT_PUBLIC_SEO_DISABLED --build-arg NEXT_PUBLIC_API_URI=$NEXT_PUBLIC_API_URI --build-arg NEXT_PUBLIC_URI=$NEXT_PUBLIC_URI --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL --cpu-shares=300 --memory=5096m  -t  acteurs-de-la-transition-client:recette .
    - cd /home/debian/docker/acteurs-de-la-transition/
    - docker-compose up -d
  only:
    - develop

push_image_and_deploy:
  script:
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - docker build --build-arg NEXT_PUBLIC_SEO_DISABLED=false --build-arg NEXT_PUBLIC_API_URI=$NEXT_PUBLIC_API_URI_PROD --build-arg NEXT_PUBLIC_URI=$NEXT_PUBLIC_URI_PROD --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL_PROD --cpu-shares=300 --memory=5096m  -t  skapyo02/acteurs-de-la-transition-client:prod .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    - docker push skapyo02/tour-alternatiba-frontend:prod
    #- ssh -o StrictHostKeyChecking=no yoan@nausicaa.alternatiba.eu 'cd /home/docker/tour && docker pull skapyo02/tour-alternatiba-frontend:prod && docker compose up -d'
  only:
    - main

variables:
  GIT_SSL_NO_VERIFY: '1'
